server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Referer"
            allowedMethods:
              - POST
              - GET
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: Customer Login
          uri: lb://FACTURAS
          predicates:
            - Path=/facturas/**
        - id: Customer Registration
          uri: lb://CLIENTES
          predicates:
            - Path=/clientes/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
# server:
#   port: 8080

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka

# spring:
#   application:
#     name: gateway-service
#   cloud:
#     gateway:
#       routes:
#         - id: facturas
#           uri: lb://FACTURAS
#           predicates:
#             - Path=/facturas*
#         - id: clientes
#           uri: lb://CLIENTES
#           predicates:
#             - Path=/clientes*
