server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # discovery:
      #   locator:
      #     enabled: true
      #     lower-case-service-id: true
      # default-filters:
      #   - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      # globalcors:
      #   corsConfigurations:
      #     "[/**]":
      #       allowedOrigins: "http://localhost:4200"
      #       allowedMethods:
      #         - POST
      #         - GET
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders: "*"
      #       allowCredentials: true
      routes:
        - id: facturas
          uri: lb://FACTURAS
          predicates:
            - Path=/facturas*
        - id: clientes
          uri: lb://CLIENTES
          predicates:
            - Path=/clientes*
